spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
#      config:
#        enabled: true
#        sources:
#          - name: hello-world-config
#        namespace: raskub-app
#      secrets:
#        enable-api: true
#        sources:
#          - name: hello-world-secret
#        namespace: raskub-app

sec:
  custom:
    message: ${SECURITY_MESSAGE}